/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7de08986-46c7-404e-9ef1-fd4b9901759e",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_pgndrrYbS",
    "aws_user_pools_web_client_id": "6t7epbp6tc70anaugajf2q8hf7",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yr3bl3zcebgclpmcezcv55oi3u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gdkpyjncsfbxdisa52wvye5mve",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://iyyvhhh2e6.execute-api.us-east-2.amazonaws.com/interm",
            "region": "us-east-2"
        }
    ],
    "aws_user_files_s3_bucket": "darryl249330c1ea8ad45e6b4f97707cb1a2444154855-interm",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
