/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:05efeb43-a6be-432c-8c02-e0cc1b336e54",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_V0Ai9ih5a",
    "aws_user_pools_web_client_id": "11bag7ta6vrbpcl4hh0b5ldqmj",
    "oauth": {}
};


export default awsmobile;
